<?php
session_start();
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/themes.php';
if (!isset($_SESSION['logged_in'])) exit;

$admin_commands = [
    'settime' => ['pattern' => '/settime [0-23]', 'handler' => 'SetWorldTime(hour);', 'desc' => '⏰ تغيير الوقت العالمي'],
    'setweather' => ['pattern' => '/setweather [0-255]', 'handler' => 'SetWeather(weatherid);', 'desc' => '🌤️ تغيير الطقس'],
    'givecash' => ['pattern' => '/givecash [id] [amount]', 'handler' => 'GivePlayerMoney(playerid, amount);', 'desc' => '💰 إعطاء نقود'],
    'teles' => ['pattern' => '/teles [x] [y] [z]', 'handler' => 'SetPlayerPos(playerid, x, y, z);', 'desc' => '📍 النقل الفوري'],
    'setskin' => ['pattern' => '/setskin [id] [skin]', 'handler' => 'SetPlayerSkin(playerid, skinid);', 'desc' => '👤 تغيير السكين'],
    'slap' => ['pattern' => '/slap [id]', 'handler' => 'SlapPlayer(playerid);', 'desc' => '😆 اضطراب اللاعب'],
    'explode' => ['pattern' => '/explode [id]', 'handler' => 'ExplodePlayer(playerid);', 'desc' => '💣 إفلاسحة اللاعب'],
    'freeze' => ['pattern' => '/freeze [id]', 'handler' => 'TogglePlayerControllable(playerid, 0);', 'desc' => '❄️ تجميد اللاعب'],
    'unfreeze' => ['pattern' => '/unfreeze [id]', 'handler' => 'TogglePlayerControllable(playerid, 1);', 'desc' => '🔥 تغيير تجميد اللاعب'],
    'goto' => ['pattern' => '/goto [id]', 'handler' => 'SetPlayerPos(playerid, targetx, targety, targetz);', 'desc' => '🚀 الذهاب للاعب'],
    'bring' => ['pattern' => '/bring [id]', 'handler' => 'SetPlayerPos(targetid, playerx, playery, playerz);', 'desc' => '📥 جلب اللاعب'],
    'mute' => ['pattern' => '/mute [id] [time]', 'handler' => 'MutePlayer(playerid, time);', 'desc' => '🔇 كتم اللاعب'],
    'kick' => ['pattern' => '/kick [id] [reason]', 'handler' => 'KickPlayer(playerid);', 'desc' => '🚪 طرد اللاعب'],
    'ban' => ['pattern' => '/ban [id] [reason]', 'handler' => 'BanPlayer(playerid);', 'desc' => '🔨 حظر اللاعب'],
];

$theme = apply_turbo_theme();

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['generate_all'])) {
    $code = "// Admin Commands - Generated by TURBO HOSTING\n// Maximum Performance Edition\n\n";
    
    foreach ($admin_commands as $key => $cmd) {
        $code .= <<<PAWN
public OnPlayerCommandText(playerid, cmdtext[])
{
    if (IsPlayerAdmin(playerid))
    {
        if (strcmp(cmdtext, "{$cmd['pattern']}", true) == 0)
        {
            {$cmd['handler']}
            SendClientMessage(playerid, 0x00FFFFAA, "✅ تم التنفيذ بواسطة تيربو هاوستينج!");
            return 1;
        }
    }
    return 0;
}

PAWN;
    }
    
    file_put_contents(__DIR__ . "/servers/server1/gamemodes/admin_cmds_turbo.pwn", $code);
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>⚡ مولد أوامر الإدارة النهائي - تيربو هاوستينج</title>
    <style>
        :root {
            --bg-gradient: <?= $theme['bg_gradient'] ?>;
            --card: <?= $theme['card'] ?>;
            --text: <?= $theme['text'] ?>;
            --accent: <?= $theme['accent'] ?>;
            --success: <?= $theme['success'] ?>;
            --danger: <?= $theme['danger'] ?>;
            --glow: <?= $theme['glow'] ?>;
        }
        body { 
            font-family: 'Segoe UI', Tahoma, sans-serif; 
            background: var(--bg-gradient); 
            color: var(--text); 
            padding: 20px;
            min-height: 100vh;
        }
        .admin-box { 
            background: var(--card); 
            padding: 25px; 
            border-radius: 15px;
            border: 2px solid var(--accent);
            box-shadow: var(--glow);
        }
        .cmd-item {
            display: flex;
            justify-content: space-between;
            padding: 10px;
            margin: 5px 0;
            background: #000;
            border-radius: 8px;
            border-right: 3px solid var(--accent);
        }
        .cmd-item:hover {
            box-shadow: var(--glow);
        }
        button { 
            padding: 12px 25px; 
            background: var(--success); 
            color: #000; 
            border: 2px solid var(--accent);
            border-radius: 8px;
            cursor: pointer; 
            font-weight: bold;
            text-transform: uppercase;
            transition: all 0.3s ease;
        }
        button:hover {
            box-shadow: var(--glow);
            transform: scale(1.05);
        }
        h2 {
            color: var(--accent);
            text-shadow: var(--glow);
            margin-bottom: 20px;
        }
        a {
            color: var(--accent);
            text-decoration: none;
        }
        a:hover {
            text-shadow: var(--glow);
        }
        code {
            color: var(--accent);
            background: #000;
            padding: 2px 8px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <a href="turbo_housting.php">🏠 العودة للوحة التحكم</a>
    <div class="admin-box">
        <h2>⚡ مولد أوامر الإدارة النهائي - تيربو هاوستينج</h2>
        <form method="POST">
            <button type="submit" name="generate_all">🚀 توليد جميع أوامر الإدارة بوضع تيربو</button>
        </form>
        <h3 style="margin-top:20px; color:var(--accent);">📋 الأوامر المتوفرة (15 أمر):</h3>
        <?php foreach ($admin_commands as $cmd): ?>
        <div class="cmd-item">
            <code><?= htmlspecialchars($cmd['pattern']) ?></code>
            <span><?= htmlspecialchars($cmd['desc']) ?></span>
        </div>
        <?php endforeach; ?>
    </div>
</body>
</html>