<?php
// MySQL Database Manager for SA-MP
require_once __DIR__ . '/config.php';
if (!isset($_SESSION['logged_in'])) exit;

$server_name = $_GET['server'] ?? $config['default_server'];
$db_file = __DIR__ . "/servers/{$server_name}/database.json";

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $config = [
        'host' => $_POST['db_host'] ?? 'localhost',
        'user' => $_POST['db_user'] ?? 'root',
        'pass' => $_POST['db_pass'] ?? '',
        'name' => $_POST['db_name'] ?? 'samp',
    ];
    file_put_contents($db_file, json_encode($config));
}

function get_db_config($server) {
    $file = __DIR__ . "/servers/{$server}/database.json";
    return file_exists($file) ? json_decode(file_get_contents($file), true) : null;
}

function generate_db_code($server) {
    $code = <<<PAWN
// MySQL Connection - Generated by Panel
new DBConnection;

public OnGameModeInit()
{
    // Connect to MySQL
    DBConnection = mysql_connect("{{host}}", "{{user}}", "{{pass}}", "{{name}}");
    if (DBConnection == -1)
    {
        print("Failed to connect to database");
    }
    else
    {
        print("Connected to database");
    }
    return 1;
}

stock GetPlayerData(playerid)
{
    new query[256];
    format(query, sizeof(query), "SELECT * FROM players WHERE id = %d", playerid);
    mysql_query(query);
}
PAWN;
    return $code;
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>قاعدة البيانات</title>
    <style>
        body { font-family: Arial; background:#1a1a2e; color:#fff; padding:20px; }
        .db-box { background:#16213e; padding:20px; border-radius:10px; }
        input { width:100%; padding:10px; margin:5px 0; background:#000; color:#fff; border:1px solid #0f0; }
        button { padding:10px 15px; background:#00aa00; color:#fff; border:none; cursor:pointer; margin:5px; }
    </style>
</head>
<body>
    <a href="index.php">العودة للوحة التحكم</a>
    <div class="db-box">
        <h2>قاعدة البيانات - <?= htmlspecialchars($server_name) ?></h2>
        <form method="POST">
            <input type="text" name="db_host" placeholder="الخادم" value="localhost">
            <input type="text" name="db_user" placeholder="المستخدم" value="root">
            <input type="password" name="db_pass" placeholder="كلمة السر">
            <input type="text" name="db_name" placeholder="اسم قاعدة البيانات" value="samp">
            <button type="submit">حفظ الإعدادات</button>
        </form>
        <h3 style="margin-top:20px;">توليد كود PAWN</h3>
        <textarea readonly style="width:100%;height:200px;"><?= htmlspecialchars(generate_db_code($server_name)) ?></textarea>
    </div>
</body>
</html>