<?php
// GameMode Generator with Templates
require_once __DIR__ . '/config.php';
if (!isset($_SESSION['logged_in'])) exit;

$templates = [
    'rp' => [
        'name' => 'Roleplay',
        'code' => 'public OnGameModeInit() { SetGameModeText("RP Server"); }',
    ],
    'tdm' => [
        'name' => 'Team Deathmatch',
        'code' => 'public OnGameModeInit() { SetGameModeText("TDM Server"); }',
    ],
    'race' => [
        'name' => 'Race',
        'code' => 'public OnGameModeInit() { SetGameModeText("Race Server"); }',
    ],
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['template'], $_POST['name'])) {
    $template = $_POST['template'];
    $name = $_POST['name'];
    $code = $templates[$template]['code'] ?? '';
    
    $full_code = <<<PAWN
// Generated by SA-MP Panel
// Template: {$templates[$template]['name']}

#include <a_samp>

public OnGameModeInit()
{
    {$code}
    print("GameMode {$name} loaded!");
    return 1;
}

public OnGameModeExit() { return 1; }
PAWN;
    
    $server_dir = __DIR__ . "/servers/server1/gamemodes";
    if (!is_dir($server_dir)) mkdir($server_dir, 0755, true);
    file_put_contents("{$server_dir}/{$name}.pwn", $full_code);
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>مولد الجيم مود</title>
    <style>
        body { font-family: Arial; background:#1a1a2e; color:#fff; padding:20px; }
        .gm-box { background:#16213e; padding:20px; border-radius:10px; }
        select, input { padding:10px; margin:5px; background:#000; color:#fff; border:1px solid #0f0; }
        button { padding:10px 15px; background:#00aa00; color:#fff; border:none; cursor:pointer; }
    </style>
</head>
<body>
    <a href="index.php">العودة للوحة التحكم</a>
    <div class="gm-box">
        <h2>مولد الجيم مود</h2>
        <form method="POST">
            <select name="template">
                <?php foreach ($templates as $key => $data): ?>
                <option value="<?= $key ?>"><?= htmlspecialchars($data['name']) ?></option>
                <?php endforeach; ?>
            </select>
            <input type="text" name="name" placeholder="اسم الجيم مود" required>
            <button type="submit">إنشاء</button>
        </form>
    </div>
</body>
</html>