<?php
// Full Gamemode Generator with Database Support
require_once __DIR__ . '/config.php';
if (!isset($_SESSION['logged_in'])) exit;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name = $_POST['gm_name'];
    $use_db = isset($_POST['use_db']);
    $use_fs = $_POST['fs_list'] ?? [];
    
    $fs_include = '';
    foreach ($use_fs as $fs) {
        $fs_include .= "#include <{$fs}>\n";
    }
    
    $code = <<<PAWN
// {$name} GameMode - Generated by SA-MP Panel

#define FILTERSCRIPT false

{$fs_include}

#if defined FILTERSCRIPT
    #define FS
#else
    #define GM
#endinput

new DB:DatabaseHandle;

public OnGameModeInit()
{
    SetGameModeText("{$name}");
    SetTimer("UpdateCheck", 60000, true);
    
    {$use_db ? "DatabaseHandle = mysql_connect(\"localhost\", \"root\", \"\", \"samp\");\n    mysql_log(LOG_ERROR | LOG_WARNING | LOG_DEBUG);" : "// No database"}
    
    // Load interiors
    for (new i = 0; i < 100; i++)
    {
        DisableInteriorEnterExits();
    }
    
    return 1;
}

public OnGameModeExit()
{
    {$use_db ? "mysql_close(DatabaseHandle);" : "// No database"}
    return 1;
}

forward UpdateCheck();
public UpdateCheck()
{
    // Periodic updates
}
PAWN;
    
    file_put_contents(__DIR__ . "/servers/server1/gamemodes/{$name}.pwn", $code);
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>مولد الجيم مود الكامل</title>
    <style>
        body { font-family: Arial; background:#1a1a2e; color:#fff; padding:20px; }
        .gm-box { background:#16213e; padding:20px; border-radius:10px; }
        input { padding:10px; margin:5px 0; background:#000; color:#fff; border:1px solid #0f0; }
        button { padding:10px 15px; background:#00aa00; color:#fff; border:none; cursor:pointer; }
    </style>
</head>
<body>
    <a href="index.php">العودة للوحة التحكم</a>
    <div class="gm-box">
        <h2>مولد الجيم مود الكامل</h2>
        <form method="POST">
            <input type="text" name="gm_name" placeholder="اسم الجيم مود" required>
            <label><input type="checkbox" name="use_db"> استخدام قاعدة البيانات</label>
            <input type="text" name="fs_list[]" placeholder="فلاتر إضافية (مثلاً: sscanf)">
            <button type="submit">إنشاء جيم مود كامل</button>
        </form>
    </div>
</body>
</html>