<?php
// Map Generator
require_once __DIR__ . '/config.php';
if (!isset($_SESSION['logged_in'])) exit;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['map_name'])) {
    $name = $_POST['map_name'];
    $objects = $_POST['objects'] ?? 100;
    
    $code = <<<PAWN
// Map: {$name}
// Generated by SA-MP Panel

public OnGameModeInit()
{
    // Create map objects
    CreateMapObjects();
    return 1;
}

stock CreateMapObjects()
{
    new Float:x, Float:y, Float:z;
    for (new i = 0; i < {$objects}; i++)
    {
        x = float(random(6000)) - 3000.0;
        y = float(random(6000)) - 3000.0;
        z = 0.0;
        
        CreateObject(1221, x, y, z, 0.0, 0.0, 0.0); // Palm tree
    }
}
PAWN;
    
    $map_dir = __DIR__ . "/servers/server1/gamemodes";
    file_put_contents("{$map_dir}/{$name}.pwn", $code);
    
    // Also create .map file format for MTA/optional
    $map_data = <<<MAP
<map name="{$name}">
    <objs>
MAP;
    for ($i = 0; $i < 10; $i++) {
        $x = rand(-3000, 3000);
        $y = rand(-3000, 3000);
        $map_data .= "<obj model=\"1221\" x=\"{$x}\" y=\"{$y}\" z=\"0\" rx=\"0\" ry=\"0\" rz=\"0\"/>\n";
    }
    $map_data .= "</objs></map>";
    
    $server_dir = __DIR__ . "/servers/server1";
    file_put_contents("{$server_dir}/{$name}.map", $map_data);
    
    $message = "تم إنشاء الخريطة";
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>مولد الخريطة</title>
    <style>
        body { font-family: Arial; background:#1a1a2e; color:#fff; padding:20px; }
        .map-box { background:#16213e; padding:20px; border-radius:10px; }
        input { width:100%; padding:10px; margin:5px 0; background:#000; color:#fff; border:1px solid #0f0; }
        button { padding:10px 15px; background:#0f3460; color:#fff; border:none; cursor:pointer; }
    </style>
</head>
<body>
    <a href="index.php">العودة للوحة التحكم</a>
    <div class="map-box">
        <h2>مولد الخرائط</h2>
        <?php if (isset($message)): ?><p style="color:#0f0;"><?= $message ?></p><?php endif; ?>
        <form method="POST">
            <input type="text" name="map_name" placeholder="اسم الخريطة" required>
            <input type="number" name="objects" placeholder="عدد الأكسسوارات" value="100">
            <button type="submit">إنشاء الخريطة</button>
        </form>
    </div>
</body>
</html>