<?php
session_start();
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/themes.php';
if (!isset($_SESSION['logged_in'])) exit;

$quick_cmds = [
    'announce' => ['cmd' => 'announce', 'desc' => '📢 إعلان عام', 'params' => 'message'],
    'weather' => ['cmd' => 'weather', 'desc' => '🌤️ تغيير الطقس', 'params' => 'weather_id'],
    'time' => ['cmd' => 'time', 'desc' => '⏰ تغيير الوقت', 'params' => 'hour minute'],
    'gravity' => ['cmd' => 'gravity', 'desc' => '🌍 الجاذبية', 'params' => 'value'],
    'map' => ['cmd' => 'map', 'desc' => '🗺️ تغيير الخريطة', 'params' => 'mapname'],
    'loadfs' => ['cmd' => 'loadfs', 'desc' => '📥 تحميل فلاتر', 'params' => 'fsname'],
    'unloadfs' => ['cmd' => 'unloadfs', 'desc' => '📤 إلغاء تحميل فلتر', 'params' => 'fsname'],
    'exec' => ['cmd' => 'exec', 'desc' => '📂 تنفيذ ملف', 'params' => 'filename'],
    'reload' => ['cmd' => 'reload', 'desc' => '🔄 إعادة التحميل', 'params' => 'fsname'],
    'savecoords' => ['cmd' => 'savecoords', 'desc' => '📍 حفظ الإحداثيات', 'params' => ''],
    'gotocoords' => ['cmd' => 'gotocoords', 'desc' => '🎯 الذهاب للإحداثيات', 'params' => 'x y z'],
    'jetpack' => ['cmd' => 'jetpack', 'desc' => '🎒 الجطار الجاهز', 'params' => ''],
    'weapon' => ['cmd' => 'weapon', 'desc' => '🔫 إعطاء سلاح', 'params' => 'weapon_id ammo'],
    'health' => ['cmd' => 'health', 'desc' => '❤️ إعادة الصحة', 'params' => 'amount'],
    'armour' => ['cmd' => 'armour', 'desc' => '🦺 إعطاء درع', 'params' => 'amount'],
];

$theme = apply_turbo_theme();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $code = "// Quick Commands - Generated by TURBO HOSTING\n// Maximum Performance Edition\n\n";
    
    foreach ($_POST['commands'] ?? [] as $cmd_key) {
        $cmd = $quick_cmds[$cmd_key]['cmd'];
        $code .= <<<PAWN
public OnPlayerCommandText(playerid, cmdtext[])
{
    if (strcmp(cmdtext, "/{$cmd}", true) == 0)
    {
        // {$quick_cmds[$cmd_key]['desc']} - TURBO MODE
        return 1;
    }
    return 0;
}

PAWN;
    }
    
    file_put_contents(__DIR__ . "/servers/server1/gamemodes/quick_commands_turbo.pwn", $code);
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>⚡ مولد الأوامر السريعة النهائي - تيربو هاوستينج</title>
    <style>
        :root {
            --bg-gradient: <?= $theme['bg_gradient'] ?>;
            --card: <?= $theme['card'] ?>;
            --text: <?= $theme['text'] ?>;
            --accent: <?= $theme['accent'] ?>;
            --success: <?= $theme['success'] ?>;
            --warning: <?= $theme['warning'] ?>;
            --glow: <?= $theme['glow'] ?>;
        }
        body { 
            font-family: 'Segoe UI', Tahoma, sans-serif; 
            background: var(--bg-gradient); 
            color: var(--text); 
            padding: 20px;
            min-height: 100vh;
        }
        .cmd-box { 
            background: var(--card); 
            padding: 25px; 
            border-radius: 15px;
            border: 2px solid var(--accent);
            box-shadow: var(--glow);
        }
        .cmd-item {
            display: flex;
            align-items: center;
            padding: 10px;
            margin: 5px 0;
            background: #000;
            border-radius: 8px;
            border-right: 3px solid var(--accent);
        }
        .cmd-item:hover {
            box-shadow: var(--glow);
        }
        .cmd-item input[type="checkbox"] {
            margin-left: 10px;
            width: 18px;
            height: 18px;
        }
        button { 
            padding: 12px 25px; 
            background: var(--success); 
            color: #000; 
            border: 2px solid var(--accent);
            border-radius: 8px;
            cursor: pointer; 
            font-weight: bold;
            text-transform: uppercase;
            transition: all 0.3s ease;
        }
        button:hover {
            box-shadow: var(--glow);
            transform: scale(1.05);
        }
        h2 {
            color: var(--accent);
            text-shadow: var(--glow);
            margin-bottom: 20px;
        }
        a {
            color: var(--accent);
            text-decoration: none;
        }
        a:hover {
            text-shadow: var(--glow);
        }
    </style>
</head>
<body>
    <a href="turbo_housting.php">🏠 العودة للوحة التحكم</a>
    <div class="cmd-box">
        <h2>⚡ مولد الأوامر السريعة النهائي - تيربو هاوستينج</h2>
        <form method="POST">
            <?php foreach ($quick_cmds as $key => $data): ?>
            <label class="cmd-item">
                <input type="checkbox" name="commands[]" value="<?= $key ?>">
                <span><?= htmlspecialchars($data['desc']) ?> (/<?= htmlspecialchars($data['cmd']) ?>)</span>
            </label>
            <?php endforeach; ?>
            <button type="submit">🚀 توليد جميع الأوامر المحددة</button>
        </form>
    </div>
</body>
</html>