<?php
require_once __DIR__ . '/config.php';
if (!isset($_SESSION['logged_in'])) {
    header('Location: index.php');
    exit;
}

$server_name = $_GET['server'] ?? $config['default_server'];
$server_dir = __DIR__ . "/servers/{$server_name}";
$message = '';

function get_server_config($server_dir) {
    $cfg_file = "{$server_dir}/server.cfg";
    if (!file_exists($cfg_file)) return [];
    return file($cfg_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $rules = [
        'No cheating',
        'Respect all players', 
        $_POST['custom_rule'] ?? ''
    ];
    
    $rules_content = "# Server Rules\n# Generated by SA-MP Panel\n\n";
    $rules_content .= "hostname " . ($_POST['hostname'] ?? '') . "\n";
    $rules_content .= "gamemode0 " . ($_POST['gamemode'] ?? 'default') . " 1\n\n";
    $rules_content .= "rules\n";
    foreach (array_filter($rules) as $rule) {
        $rules_content .= "{$rule}\n";
    }
    
    file_put_contents("{$server_dir}/rules.cfg", $rules_content);
    $message = "تم حفظ القوانين";
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>القوانين والـ Announcements</title>
    <style>
        body { font-family: Arial; background:#1a1a2e; color:#fff; padding:20px; }
        .rules-box { background:#16213e; padding:20px; border-radius:10px; }
        textarea { width:100%; height:150px; background:#000; color:#0f0; border:1px solid #0f0; padding:10px; }
        input { width:100%; padding:10px; background:#000; color:#fff; border:1px solid #0f0; margin:5px 0; }
        button { padding:10px 15px; background:#00aa00; color:#fff; border:none; cursor:pointer; margin:5px; }
    </style>
</head>
<body>
    <a href="index.php">العودة للوحة التحكم</a>
    <div class="rules-box">
        <h2>القوانين والإعلانات - <?= htmlspecialchars($server_name) ?></h2>
        <?php if ($message): ?>
        <p style="color:#0f0;"><?= $message ?></p>
        <?php endif; ?>
        <form method="POST">
            <h3>الإعلانات</h3>
            <input type="text" name="hostname" placeholder="اسم الخادم">
            <input type="text" name="gamemode" placeholder="الجيم مود" value="default">
            <textarea name="custom_rule" placeholder="قاعدة مخصصة..."></textarea>
            <button type="submit">حفظ</button>
        </form>
    </div>
</body>
</html>