<?php
// SSCANF Format Generator
require_once __DIR__ . '/config.php';
if (!isset($_SESSION['logged_in'])) exit;

$formats = [
    'player_selector' => ['format' => "sscanf(params, "i", playerid)"],
    'coord' => ['format' => "sscanf(params, "fff", x, y, z)"],
    'string' => ['format' => "sscanf(params, "s", text)"],
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['format'])) {
    $code = <<<PAWN
// Generated by SA-MP Panel
public OnPlayerCommandText(playerid, cmdtext[])
{
    new params[128];
    new idx;
    cmdtext = strtok(cmdtext, " ");
    while (cmdtext)
    {
        params[idx++] = cmdtext;
        cmdtext = strtok(" ");
    }
    
    if (strcmp(params[0], "/{$_POST['command']}", true) == 0)
    {
        {$_POST['format']}
        return 1;
    }
    return 0;
}
PAWN;
    
    file_put_contents(__DIR__ . "/servers/server1/gamemodes/sscanf_{$_POST['command']}.pwn", $code);
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>مولد SSCANF</title>
    <style>
        body { font-family: Arial; background:#1a1a2e; color:#fff; padding:20px; }
        .sscanf-box { background:#16213e; padding:20px; border-radius:10px; }
        input, textarea { width:100%; padding:10px; margin:5px 0; background:#000; color:#fff; border:1px solid #0f0; }
        button { padding:10px 15px; background:#aa5500; color:#fff; border:none; cursor:pointer; }
    </style>
</head>
<body>
    <a href="index.php">العودة للوحة التحكم</a>
    <div class="sscanf-box">
        <h2>مولد SSCANF</h2>
        <form method="POST">
            <input type="text" name="command" placeholder="اسم الأمر" required>
            <textarea name="format" placeholder="كود SSCANF..."></textarea>
            <button type="submit">إنشاء</button>
        </form>
    </div>
</body>
</html>